services:
  - type: web
    name: resume-builder-backend
    env: node
    branch: main
    rootDir: server
    buildCommand: npm install
    startCommand: node server.js

  - type: web
    name: resume-builder-frontend
    env: static
    branch: main
    rootDir: client
    staticPublishPath: dist
    buildCommand: npm install && npm run build
